### ISSUE TITLE
Initialize a map

### ISSUE THREAD

**Issue by emilymdubois** [dylanlewis89/native_names#1]
- [x] Sign up for a [mapbox.com](https://www.mapbox.com/) account
- [x] Grab your public access token (hint: it's in the settings 😉)
- [x] Initialize a map

We're going to use Mapbox GL JS to create our first map. Start with the code presented in [this first example](https://www.mapbox.com/mapbox-gl-js/examples/), and we'll go from there!

**Comment by dylanlewis89** [comment]
Boom, toasted.

**Comment by emilymdubois** [comment]
Yay! Wanna push your work to a branch?

**Comment by emilymdubois** [comment]
Closed via [PR #2](https://github.com/dylanlewis89/native_names/pull/2)
